# Generated by Django 3.2.3 on 2021-05-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='categor',
            new_name='cat_fk',
        ),
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers', verbose_name='Обложка'),
        ),
    ]
