# Generated by Django 3.2.3 on 2021-05-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210530_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book_category',
            new_name='BookCategory',
        ),
    ]
