# Generated by Django 3.2.4 on 2021-07-06 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20210629_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 5, 16, 9, 863120, tzinfo=utc)),
        ),
    ]
