# Generated by Django 3.2.5 on 2021-07-08 10:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_bookuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 10, 37, 13, 273502, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='BookUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='Теги')),
                ('about_me', models.TextField(blank=True, max_length=32767, verbose_name='О себе')),
                ('gender', models.CharField(blank=True, choices=[('m', 'М'), ('w', 'Ж')], max_length=1, verbose_name='пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
